issue #328: add user/password authentication (Redis 6 ACL feature)
RedisLabs/spark-redis pull request #333
Opened 2021-12-15 23:42 UTC by fe2s

2021-12-18 20:41 UTC, gkorland requested changes

2021-12-18 20:41 UTC, gkorland commented on pom.xml
> +		<jedis.version>3.7.0</jedis.version>
```suggestion
		<jedis.version>3.7.1</jedis.version>
```

2021-12-21 09:51 UTC, sazzad16 requested changes

2021-12-21 09:51 UTC, sazzad16 commented on pom.xml
> +		<jedis.version>3.7.1</jedis.version>
```suggestion
		<jedis.version>3.8.0</jedis.version>
```

2022-01-13 11:19 UTC, sazzad16 approved these changes

2022-01-14 16:05 UTC, gkorland approved these changes

2022-01-14 16:07 UTC, merged